# Generated by Django 3.0.2 on 2020-01-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.CharField(default='/activity_placeholder.jpg', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(default='/avatar_placeholder.png', max_length=100),
        ),
    ]
